exclude: [README.md, package.json, bower.json, Gruntfile.js, node_modules, assets/**/src]
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
